version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: front
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
